### ISSUE TITLE
Make md2beamer easier to use

### ISSUE THREAD

**Issue by puchka** [jrvarma/markdown-glue#1]
# Description

When trying to use `md2beamer`
- I had to create a symlink to `split_path` in `~/bin`
- I also had to download https://github.com/adityam/pandoc-templates/blob/master/default.beamer and put it in `~/.pandoc/templates`

# Suggestion

Make it work out of the box

**Comment by jrvarma** [comment]
Done. The Readme has also been updated with customization options.

**Comment by puchka** [comment]
I appreciate your consideration, Sir.

Regards,

Marius
